apiVersion: v1
kind: ConfigMap
metadata:
  name: roboshop-{{ .Values.componentName }}
data:
  MONGO_URL: "mongodb://mongo-mongodb:27017/catalogue"
  REDIS_HOST: redis-master
  CATALOGUE_HOST: catalogue
  CATALOGUE_PORT: "8080"
  CART_ENDPOINT: "cart:8080"
  CART_HOST: cart
  CART_PORT: "8080"
  USER_HOST: user
  AMQP_HOST: rabbitmq
  USER_PORT: "8080"
  AMQP_USER: roboshop
  AMQP_PASS: roboshop123
