apiVersion: v1
kind: Pod
metadata:
  name: sample
spec:
  containers:
    - name: nginx
      image: nginx
---
apiVersion: v1
kind: Pod
metadata:
  name: sample1
spec:
  containers:
    - name: nginx
      image: nginx
      env:
        - name: URL
          value: google.com
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sample
data:
  URL: google.com
  LOCATION: USA
  FOUNDED_BY: hameed
---
apiVersion: v1
kind: Pod
metadata:
  name: sample2
spec:
  containers:
    - name: nginx
      image: nginx
      #envFrom:
#envFrom if we want multiple values then we are using envFrom, If we want single values then env we are using
      env:
        - name: URL
          valueFrom:
            configMapKeyRef:
              key: URL
              name: sample
              ## Above name is name of configMap
---
apiVersion: v1
kind: Pod
metadata:
  name: sample3
spec:
  containers:
    - name: nginx
      image: nginx
      envFrom:
        - configMapRef:
            name: sample
#envFrom if we want multiple values then we are using envFrom, If we want single values then env we are using
