apiVersion: v1
kind: Pod
metadata:
  name: sample6
spec:
  containers:
    - name: centos
      image: centos
      command:
       - sleep 30
       - "100000"
      resources:
        requests:
          cpu: "500m"
          memory: "500mi"
        limits:
          cpu: "750m"
          memory: "750mi"
##1CPU - 1000m core